### ISSUE TITLE
Does not disable all optional packages on atom close

### ISSUE THREAD

**Issue by Gerschtli** [Gerschtli/enable-packages#1]
On `deactivate` all optional packages should be disabled. This works if you disable `enable-packages` manually or if you reload the atom window.
If you close atom, `deactivate` gets called but the config does not save the updated list `core.disabledPackages`.

I'm open for ideas how to solve this issue.

**Comment by NJT145** [comment]
Use 
_atom.packages.disablePackage(packageName)_ instead of _atom.packages.deactivate(packageName)_

**Comment by Gerschtli** [comment]
Repo is archived
